"use client"
import localFont from "next/font/local";
import "./globals.css";
import { ChakraProvider } from '@chakra-ui/react'
import { Providers } from "./ChakraProvider";
import ChatProvider from "../contextapi/chatProvider"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="backgroundImage"
      >
        <ChatProvider>
         <Providers>
           {children}
           </Providers>
           </ChatProvider>
      </body>
    </html>
  );
}
